<h4 class="cooper">THE CHEESECAKE SHOP</h4>
<h5>WIN $10000 IN VOUCHERS WITH THE CHEESECAKE SHOP PIMP UP YOUR DAD</h5>
<h5>TRADE PROMOTION</h5>
<h5>TERMS AND CONDITIONS</h5>
<p>1. Information on how to enter and prizes form part of these Terms and Conditions. Participation in this promotion is deemed acceptance of these Terms and Conditions.</p>
<p>2. Entry is only open to Australian residents. Entrants under 18 years old must have parental/guardian approval to enter and further, the parent/guardian of the entrant must read and consent to these Terms and Conditions. Parents/guardians may be required by the Promoter to enter into a further agreement as evidence of consent to the minor entering this promotion. Employees (and their immediate families) of the Promoter and agencies associated with this promotion are ineligible to enter.</p>
<p>3. Promotion commences on 05/08/2013 at 12:00 (AEDST) and closes on 08/09/2013 at 17:00 (AEDST) ("Promotional Period").</p>
<p>4. To be eligible to enter, individuals must, during the Promotional Period:</p>
<p>(a) purchase any product in any participating The Cheesecake Shop nationally that is advertising the promotion. Individuals will be given an information card at the point of purchase. It is the responsibility of the individuals to ensure that they receive an information card at point of purchase.</p>
<p>5. To enter, individuals must then, during the Promotional Period:</p>
<p>(a) visit pimpupdad.com.au and follow the prompts to the promotion entry page input the requested details including their first name, surname, contact number, receipt number, image of participant and store of purchase and submit the fully completed entry form.</p>
<p>6. Multiple entries permitted, subject to the following:</p>
<p>(a) only one (1) entry permitted per eligible transaction; and each entry must be submitted separately and in accordance with entry requirements.</p>
<p>7. The Promoter reserves the right, at any time, to verify the validity of entries and entrants (including an entrant's identity, age and place of residence) and to disqualify any entrant who submits an entry that is not in accordance with these Terms and Conditions or who tampers with the entry process. Errors and omissions may be accepted at the Promoter's discretion. Failure by the Promoter to enforce any of its rights at any stage does not constitute a waiver of those rights.</p>
<p>8. Incomplete or indecipherable entries will be deemed invalid.</p>
<p>9. Entrants must retain original receipt(s) for all entries as proof of purchase for up to fourteen (14) days after the draw date. Failure to produce the original receipt(s) for all entries when requested may, in the absolute discretion of the Promoter, result in invalidation of ALL of an entrant's entries and forfeiture of any right to a prize. Purchase receipt(s) must clearly specify the store of purchase that the purchase was made during the Promotional Period but prior to entry.</p>
<p>10. Winners will be notified in writing by mail and phone by 10/09/2013.</p>
<p>11. There is one (1) major prize to be awarded in this promotion.</p>
<p>12. The entry with the most votes from the public vote will be deemed the winner. The major prize is retail vouchers to the value of $10,000.</p>
<p>13. During the entire duration of the major prize, a nominated parent/guardian must accompany any person under 18 years of age.</p>
<p>14. As a condition of accepting the major prize, the winner (and companions) must sign any legal documentation as and in the form required by the Promoter and/or prize suppliers in their absolute discretion, including but not limited to a legal release and indemnity form.</p>
<p>15. If for any reason a winner does not take a prize (or an element of a prize) at the time stipulated by the Promoter, then the prize (or that element of the prize) will be forfeited and will not be redeemable for cash.</p>
<p>16. The total prize pool value is up to $10,000.</p>
<p>17. If a winner of a prize is under the age of 18 years, the prize will be awarded to the winner's nominated parent or guardian on the winner's behalf.</p>
<p>18. The Promoter's decision is final and no correspondence will be entered into.</p>
<p>19. If the prize is unclaimed by 2 weeks from the end date of the promotion the entry with the next greatest number of votes will deemed the winner.</p>
<p>20. Entrants consent to the Promoter using the entrant's name, likeness, image and/or voice in the event they are a winner (including photograph, film and/or recording of the same) in any media for an unlimited period without remuneration for the purpose of promoting this competition (including any outcome), and promoting any products manufactured, distributed and/or supplied by the Promoter.</p>
<p>21. If this promotion is interfered with in any way or is not capable of being conducted as reasonably anticipated due to any reason beyond the reasonable control of the Promoter, including but not limited to technical difficulties, unauthorised intervention or fraud, the Promoter reserves the right, in its sole discretion, to the fullest extent permitted by law: (a) to disqualify any entrant; or (b) subject to any written directions from a regulatory authority, to modify, suspend, terminate or cancel the promotion, as appropriate.</p>
<p>22. Any cost associated with accessing the promotional website is the entrant's responsibility and is dependent on the Internet service provider used. The use of any automated entry software or any other mechanical or electronic means that allows an entrant to automatically enter repeatedly is prohibited and will render all entries submitted by that entrant invalid.</p>
<p>23. Nothing in these Terms and Conditions limits, excludes or modifies or purports to limit, exclude or modify the statutory consumer guarantees as provided under the Competition and Consumer Act, as well as any other implied warranties under the ASIC Act or similar consumer protection laws in the State and Territories of Australia ("Non-Excludable Guarantees"). Except for any liability that cannot by law be excluded, including the Non-Excludable Guarantees, the Promoter (including its respective officers, employees and agents) excludes all liability (including negligence), for any personal injury; or any loss or damage (including loss of opportunity); whether direct, indirect, special or consequential, arising in any way out of the promotion.</p>
<p>24. Except for any liability that cannot by law be excluded, including the Non-Excludable Guarantees, the Promoter (including its respective officers, employees and agents) is not responsible for and excludes all liability (including negligence), for any personal injury; or any loss or damage (including loss of opportunity); whether direct, indirect, special or consequential, arising in any way out of: (a) any technical difficulties or equipment malfunction (whether or not under the Promoter's control); (b) any theft, unauthorised access or third party interference; (c) any entry or prize claim that is late, lost, altered, damaged or misdirected (whether or not after their receipt by the Promoter) due to any reason beyond the reasonable control of the Promoter; (d) any variation in prize value to that stated in these Terms and Conditions; (e) if any event which is part of the major prize is cancelled or delayed for any reason beyond the reasonable control of the Promoter; (f) any tax liability incurred by a winner or entrant; or (g) use of a prize.</p>
<p>25. The Promoter collects personal information in order to conduct the promotion and may, for this purpose, disclose such information to third parties, including but not limited to agents, contractors, service providers, prize suppliers and, as required, to Australian regulatory authorities. Entry is conditional on providing this information. The Promoter may, for an indefinite period, unless otherwise advised, use the information for promotional, marketing, publicity, research and profiling purposes, including sending electronic messages or telephoning the entrant. Entrants should direct any request to access, update or correct information to the Promoter. All entries become the property of the Promoter.</p>
<p>26. The Promoter is The Cheesecake Shop Pty Ltd (ABN 54 059 134 431) of 2 Lisbon Street, Villawood NSW 2163, Australia. Tel 02 9723 1011.</p>